### ISSUE TITLE
Is it possible to get data faster than 5 seconds?

### ISSUE THREAD

**Issue by DaniilPo** [no23reason/react-geolocated#1081]
I need to get the data as quickly as possible, what is the fastest way to do this?
No matter how I try, I always get only once every 5 seconds.
Perhaps there are some restrictions in the browser itself?

**Comment by no23reason** [comment]
There is nothing we do to "slow down" the data getting to the component in case the user has allowed the Geolocation API to be used, so maybe there is in fact som slow-down in the browser.
