### ISSUE TITLE
fix: problem activating the location after clicking block

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [no23reason/react-geolocated#1342]
Issue: In the prompt, if I decide to click *block* then I can’t activate the location clicking the button *Get Location*

Computer: Mac
Browser: Chrome

**Comment by no23reason** [comment]
Hi, sorry for the (very) late reply. There is not much we can do about this, if the user decides to block the permission, the Javascript code cannot ask for it again. The only thing the user can do to change their decision is to allow the geolocation (there is usually a button for this in the address bar).
