### ISSUE TITLE
Event-based prompt for user location, instead of immediately on page load?

### ISSUE THREAD

**Issue by PatNeedham** [no23reason/react-geolocated#155]
I would like there to be an option so that the browser prompt
![image](https://user-images.githubusercontent.com/967811/31660395-47b99a18-b305-11e7-9135-5873f1704bd5.png)
does not appear right away, but instead as a result of a button click or any other user-generated action.

Can there be a function prop (with 3 callback arguments) that triggers the prompt being asked? Something like
```
function determineLocation() {
  this.props.showLocationPrompt(this.allowed, this.blocked, this.closed)
}
function allowed() {
  // user clicked allow (or had previously given permission to this site to access location)
}
function blocked(firstTime) {
  if (firstTime) {
    // user clicked the Block option
  } else {
    // attempt blocked because of prior blocking
  }
}
function closed() {
  // user chose neither Block or Allow, must have closed the prompt
}
```

For that `blocked` function I think including a firstTime argument is necessary (not sure how to access it from browser settings though). When I was testing on localhost, I never saw the prompt to begin with, because it turns out I had previously blocked it and only found that out after looking at the site settings in Chrome:
![image](https://user-images.githubusercontent.com/967811/31662714-8a971c0e-b30d-11e7-9f61-69c68f392d1e.png)

Knowing whether the location request was blocked by clicking "Block" or due to prior clicking would allow for a more appropriate response message, such as "You have blocked access to location, unable to proceed" vs "You have previously blocked access to location. Please click on Site settings -> Location -> Always allow on this site." [slightly different message depending on the browser].

**Comment by no23reason** [comment]
Thank you for the suggestion, however I believe that this would be impossible to do reliably in all the browsers. For example Firefox does not even tell you anything when the user clicks block (that is one of the reasons the `userDecisionTimeout` config property was introduced). For this reason it would be quite hard deciding whether to call `closed` or `blocked` :-/

The location is not queried on page load but [on mount of the Geolocated HOC](https://github.com/no23reason/react-geolocated/blob/master/src/components/geolocated.js#L68) (which can happen later).

There could be a method like `getLocation` exposed to be used using a `ref` in the parent component and a configuration property like `suppressLocationOnMount` that would disable the location query on mount and you would have to call the `getLocation` explicitly whenever you wanted.

What do you think of this approach?

**Comment by PatNeedham** [comment]
The approach you proposed does sound more reasonable. As long as `suppressLocationOnMount` has a default value of `false`, it shouldn't break any other break any existing functionality right?
