### ISSUE TITLE
Warning in Server Side Rendered Setup

### ISSUE THREAD

**Issue by elodingens** [no23reason/react-geolocated#157]
Hi,

in a Server Side Rendered Setup the component shows up a warning, regardless if client gets a position or not:

Warning: setState(...): Can only update a mounting component. This usually means you called setState() outside componentWillMount() on the server. This is a no-op. Please check the code for the Geolocated(MerchantSearch) component.

Can you check, if you can use the DOM before setting state?

**Comment by no23reason** [comment]
Thank you for the bug report. I haven't used this in a SSR scenario yet. Can you please provide how you use the component? I'm interested mainly in the `options` of the `geolocated` function you use.

**Comment by elodingens** [comment]
`
...
import { geolocated } from 'react-geolocated';

...
@geolocated({
    positionOptions: {
        enableHighAccuracy: false,
      },
      userDecisionTimeout: 10000,
})
class MerchantSearch extends Component {

          static propTypes = {
                  coords: PropTypes.object,
          }

}
....
`

**Comment by no23reason** [comment]
There is a new version `2.2.1` that should address this issue properly. Please try upgrading to it and see if it works for you.

**Comment by elodingens** [comment]
Hi,

thx for the fix. Works!

Have a nice day.

**Comment by no23reason** [comment]
I'm glad I could help :)
