### ISSUE TITLE
How to get the city name

### ISSUE THREAD

**Issue by mborah** [no23reason/react-geolocated#159]
I don't want the Lat Lng, I am not able to get the city name.

**Comment by no23reason** [comment]
There are API's that provide this functionality. There is [an example](https://gist.github.com/AmirHossein/92a0597b5f723b19c648) of this using the Google Maps API (see [the relevant part of the docs](https://developers.google.com/maps/documentation/javascript/geocoding#ReverseGeocoding)).

Making this functionality a part of this library is out of scope, it is meant to be as simple as possible to allow the users to use the geolocation data any way they need.

**Comment by mborah** [comment]
Thanks
