### ISSUE TITLE
Support for mobile devices

### ISSUE THREAD

**Issue by angel-git** [no23reason/react-geolocated#167]
Hello,
This library works great on desktop, is there any way to make it work for ios and android devices? I tested on both and it doesn't seem to work.
Thanks!

**Comment by no23reason** [comment]
Hello, unfortunately React Native API is [quite different](http://facebook.github.io/react-native/docs/geolocation.html), so I don't see a way of getting this library work there. A standalone library would be more useful and feasible.

**Comment by angel-git** [comment]
thanks!
