### ISSUE TITLE
support watchPosition()

### ISSUE THREAD

**Issue by codeocelot** [no23reason/react-geolocated#170]
Is there any interest in supporting [`geolocation.watchPosition()`](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition)?  It has a very similar API to getCurrentPosition() and it should be relatively painless to add support updating the component's state and de-registering the listener on componentWillUnmount.  

Happy to take a stab at it if it's something you feel is appropriate for the lib.

**Comment by no23reason** [comment]
Released as [2.3.0](https://github.com/no23reason/react-geolocated/releases/tag/v2.3.0). Thank you @codeocelot!
