### ISSUE TITLE
How do I trigger an event handler in this.props

### ISSUE THREAD

**Issue by carpiediem** [no23reason/react-geolocated#188]
I'd like to propagate the location fix to parent elements, but I can't seem to get it right.  Would it be possible to adapt the demo to make that function more clear?

**Comment by no23reason** [comment]
I'm not sure I understand what event you'd like to handle. Can you please elaborate?

**Comment by carpiediem** [comment]
[The react-geolocation library](https://github.com/tkh44/react-geolocation) has an `onSuccess` event, which allows the parent element to assign a handler to the `Geolocation` class and use the location data.  Is there an equivalent function in this library?

**Comment by no23reason** [comment]
Oh, I see what you mean. No, this is not currently supported, but would be relatively simple to add. PR would be welcome, if you want to contribute, otherwise I'll try to look into it tomorrow.
