### ISSUE TITLE
Asking for permission too soon

### ISSUE THREAD

**Issue by hosekhoshtaghaza** [no23reason/react-geolocated#206]
First many thanks for this plugin! Great job :) 

I do have one minor issue... The plugin seems to ask for permission on site load rather than waiting until someone has pressed a button that initiates this.props.isGeolocationAvailable. Anything I can do to get around this?

**Comment by no23reason** [comment]
Thank you for your kind words :)

The component asks for the permission on mount, unless the `suppressLocationOnMount` is set to `true`. So your two options are

1. Render the geolocated component after the user clicks the button
2. Use the `suppressLocationOnMount` option and explicitly initiate the location getting (see the [Configuration section of the README](https://github.com/no23reason/react-geolocated/blob/master/README.md#configuration).

I hope this solves your problem, if you run into more issues, feel free to ask :)

**Comment by hosekhoshtaghaza** [comment]
Doh! Just realised I was looking at the docs for a similarly named package. Thanks for the quick response, much appreciated!! :)
