### ISSUE TITLE
how to detect ON / OFF of gps in real time

### ISSUE THREAD

**Issue by gukii** [no23reason/react-geolocated#207]
When turning GPS on or off during operation,  this.props.isGeolocationEnabled is not toggled in real-time, the change in GPS status props is only available after page reload.

Maybe do a debounce on the prop, but its only available within the child..

**Comment by no23reason** [comment]
Hi, are you using the option `watchPosition` set to `true`?

**Comment by gukii** [comment]
I tried it with and without. When using watchPosition, I got valid coords that tracked well on the google map. Even tried to turn on and off while walking to ensure that props are getting updated, however isGeolocationEnabled prop did only update on page-reload.

Tested on Chrome-Android, latest version on Samsung S8.

**Comment by gukii** [comment]
I tried it:
```

positionOptions: {
    enableHighAccuracy: true,
  },
  watchPosition: true,
  userDecisionTimeout: 5000
}

```

**Comment by gukii** [comment]
Unfortunately, it didn t work.

**Comment by no23reason** [comment]
That is really strange, other people reported that watchPosition works as expected. Does the position itself (the coordinates) get upated with `watchPosition: true`?

**Comment by gukii** [comment]
Yes, the position gets updated.

**Comment by no23reason** [comment]
So what you are saying is that the location gets updated *and* `isGeolocationEnabled` is false?

**Comment by gukii** [comment]
the following two examples have watchPosition: true


1) when GPS is ON and the page is loaded everything works as expected.
isGeolocationEnabled shows true
coords.longitude shows position

as I walk around the coords values get updated

2) if in the next step (still on the same page without reload) i turn OFF gps:
 the props don t get updated at all. they stay the same, still showing the last position coords, and still showing isGeolocationEnabled as true

I need to reload the page to see the props getting updated to the correct values of 
isGeolocationEnabled showing false, and coords to not exist.

--------------

3) In reverse the same problem exists: 

when GPS is OFF and the page is loaded everything works as expected:
isGeolocationEnabled shows false
coords do not exist

4) if in the next step (still on the same page without reload) i turn ON gps:
 the props don t get updated at all. they stay the same, still showing isGeolocationEnabled as false and coords do not exist

when waiting and walking around this situation does not change.

I need to reload the page to see the props getting updated to the correct values of 
isGeolocationEnabled showing true, and coords to show correct values.

**Comment by no23reason** [comment]
Ok, thanks for the detailed info! I'll have a look at it as soon as I can.

**Comment by no23reason** [comment]
Closing as inactive
