### ISSUE TITLE
Does it work with nextjs?

### ISSUE THREAD

**Issue by ngocketit** [no23reason/react-geolocated#210]
Hi,

Do you have an example for using it with nextjs? To me it looks like that it won't work. Thanks!

**Comment by no23reason** [comment]
Hi, I haven't tried it. What specifically does not work for you?

**Comment by ngocketit** [comment]
It looks like `getInitialProps` is not called for some reason.

**Comment by ngocketit** [comment]
I mean when using it with nextjs pages. It seems to work with components though.

**Comment by no23reason** [comment]
I don't know much about Next. Maybe [this SO answer](https://stackoverflow.com/a/50429711/2546338) can help? I mean calling this component on server does not make much sense, right?

**Comment by no23reason** [comment]
Closing as inactive.
