### ISSUE TITLE
Not Working in chrome

### ISSUE THREAD

**Issue by kapilgundawar** [no23reason/react-geolocated#211]
Hi Team,

The code is not working in chrome from morning
even in demo page also iam not getting lat long
it is saying geoloaction is not enabled even after enabling
Attached screen short for reference
![lat long issue](https://user-images.githubusercontent.com/3367981/53474070-244a5c00-3a92-11e9-981c-b18a4ebfbd28.png)

**Comment by moshebeeri** [comment]
Same here, I also tried with Safari, and its not working, maybe its not working with mac at all?

**Comment by no23reason** [comment]
Hi, that is strange, it works on my machine (MacBook Pro 2018, Chrome 72.0.3626.119, latest Safari). Did you allow the position usage using the popup (see screenshot)?
![image](https://user-images.githubusercontent.com/1748653/53578935-ed02aa80-3b78-11e9-97fc-d591c4e753a6.png)

**Comment by althafib** [comment]
same here... even if i allow  position usage using the popup... but some times it works fine

**Comment by matteofrana** [comment]
I have the same problem on an e-commerce just released in beta: 60% of users seems to have it working and 40% not: even if they enable the geolocation, I receive `isGeolocationEnabled`: false.
I'll try logging with the `onSuccess` callback. Unfortunately it is not easy to reproduce.

**Comment by no23reason** [comment]
@matteofrana I'm sad that it behaves so weirdly all of the sudden :-/ any additional information could help us figure out what is wrong. Thank you for helping!

**Comment by dzonekl** [comment]
Reporting not working, even after allowing location popup dialog, both chrome and safari.

**Comment by no23reason** [comment]
Apparently, this is a Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=753242

**Comment by dzonekl** [comment]
Oh indeed thanks, now we can track this issue there.

**Comment by no23reason** [comment]
Closing as it was a bug in Chrome
