### ISSUE TITLE
Expose getLocationPermission function

### ISSUE THREAD

**Issue by Pixelatex** [no23reason/react-geolocated#238]
Currently there is no way to easily request a new location, the whole passing through of refs in the parent is quite in-elegant. And this only seems to work once...

I have the following usecase: Map that shows the user's location and everytime they press 'relocate to my location' It should popup the location permission box if denied earlier.

**Comment by no23reason** [comment]
Hi, the ref-based solution should work (and it should work repeatedly, if it's not, please provide an example). I don't know how else I should expose the function, do you have any ideas?

**Comment by Pixelatex** [comment]
My issue was that I only had a single component file, just the app.js. It is a very small app. And since stateless components don't have access to their own 'this'....

For now I fixed it by wrapping it in another container component just to get the ref. 

If you want, I can take a look this weekend and see if I can make a PR to expose the function better? I have a few ideas that might work.

**Comment by no23reason** [comment]
Oh, I see. I'm glad you made it work :) PR would be welcome if you have the time :)

**Comment by no23reason** [comment]
Closing as inactive
