### ISSUE TITLE
Geolocation is available and enabled but coords is null

### ISSUE THREAD

**Issue by rgllm** [no23reason/react-geolocated#265]
Hello.
The geolocation is available and enabled but the coords props are null. The props object: 

```
coords: null
isGeolocationAvailable: true
isGeolocationEnabled: true
```

Any idea why this is happening? Thanks.

**Comment by no23reason** [comment]
Hello, that is strange. Is this issue present in all the browsers? How do you use the component?

**Comment by rgllm** [comment]
Hello @no23reason, thanks for the reply.
This was happening on Chrome for a limited time, I tried on Firefox and then on Chrome's private mode and the problem was solved.

**Comment by no23reason** [comment]
I'm glad it works now :)

**Comment by eddyoc** [comment]
I have the exact same issue with this hoc. Can you provide any detail on how this was resolved?

**Comment by no23reason** [comment]
It seems it was an error in a certain version of the browser.

**Comment by irishdan** [comment]
I have the same issue using latest version of chrome

**Comment by pfischer1290** [comment]
This is because chrome blocks non-secure connections from retrieving geo-location.
Probably happens on localhost?

Try to set the domain here: chrome://flags/#unsafely-treat-insecure-origin-as-secure

then it should work as expected.

**Comment by manavpandya1995** [comment]
Nope, getting the same issue event after trying the resolution given by @pfischer1290 

@no23reason please look into it

**Comment by mattvb91** [comment]
This issue still exists has anyone managed to fix it properly?
