### ISSUE TITLE
demo page not working  

### ISSUE THREAD

**Issue by lucasverra** [no23reason/react-geolocated#304]
![image](https://user-images.githubusercontent.com/11323803/64520576-bb705600-d2f6-11e9-86bc-c605f8483df3.png)

**Comment by no23reason** [comment]
Thank you for reporting this! I'll take a look at this as soon as I can.

**Comment by no23reason** [comment]
Blocked by https://github.com/doczjs/docz/issues/763

**Comment by cowglow** [comment]
Shouldn't this issue be closed? The demo works, but not with the `/demo` in the URL.

**Comment by no23reason** [comment]
Unfortunately, the fact that the demo works without the `/demo` was added as a temporary workaround for this (so that the demo is reachable). However, this is not ideal, and the demo should not be on the main page (because it immediately asks for location, which can seem wrong to some people).

**Comment by no23reason** [comment]
Fixed in #963 by rewriting the demo application, now there are no routes.
