### ISSUE TITLE
React Hooks Support 

### ISSUE THREAD

**Issue by MufassirShaw** [no23reason/react-geolocated#414]
Really Surprised that this package doesn't have anything that starts with **use**.
Are you gonna add that anytime soon?

Thanks for the package though

**Comment by no23reason** [comment]
I considered it in the past, but there were some architectural challenges with it. I will take another look at it over the weekend and let you know :)

**Comment by MufassirShaw** [comment]
Really looking forward to it.

**Comment by no23reason** [comment]
Hi, I looked into it and I believe the hook can be done, I just don't really know how to make it so, that the HOC users are not negatively affected. To be honest, I still think the HOC is the better way to go here. Do you have any particular use case that you cannot solve using the HOC?

**Comment by MufassirShaw** [comment]
Well there is only one issue which is inherent to HOCs, and throws me off of it is the way your code look when you have multiple wrapper components, in my case i had to use antd's [form.create](https://ant.design/components/form/) hoc and this one as well which required me to move my code quite a bit.
 Otherwise it works perfectly :)

**Comment by no23reason** [comment]
Oh, I see how that can be confusing at first :) sorry for not making the hook version, however if you are so inclined, feel free to create a standalone package for that ;)
