### ISSUE TITLE
How to use onError props?

### ISSUE THREAD

**Issue by LorhanSohaky** [no23reason/react-geolocated#415]

**Comment by no23reason** [comment]
Please see the [Demo](https://github.com/no23reason/react-geolocated/blob/master/demo/App.jsx#L14) for an example.

**Comment by LorhanSohaky** [comment]
Could I access `onError` inside wrapped component?

**Comment by no23reason** [comment]
Not really, but you can use `props.positionError` in them. Does that work for you?

**Comment by LorhanSohaky** [comment]
It works, I just thought that `onError` was passed by `props` to `geolocated`
