### ISSUE TITLE
Firefox 71.0 (64-Bit) Linux Mint "Unknown error acquiring position"

### ISSUE THREAD

**Issue by TomlDev** [no23reason/react-geolocated#431]
Hello I am using Linux Mint Tessa, with Firefox 71.0 (64-Bit) and tried your demo page 
[https://no23reason.github.io/react-geolocated/](https://no23reason.github.io/react-geolocated/)
I get the following error when clicked on the "get location" button:
```PositionError

​code: 2

​message: "Unknown error acquiring position"
​
<prototype>: PositionErrorPrototype

​​PERMISSION_DENIED: 1​​

POSITION_UNAVAILABLE: 2​​

TIMEOUT: 3
```

![grafik](https://user-images.githubusercontent.com/48552168/73269741-aa5cae80-41dd-11ea-8515-9ce5e61cbea0.png)

But Geolocation API is enabled, and site is over HTTPS
![grafik](https://user-images.githubusercontent.com/48552168/73269715-a0d34680-41dd-11ea-814a-6edbe49f415a.png)

**Comment by TomlDev** [comment]
Alright, doesnt seem to be a problem with your code, same issue on MDN:
![grafik](https://user-images.githubusercontent.com/48552168/73272760-31f8ec00-41e3-11ea-96dc-c7583fe3cf52.png)
And on Chrome it works for me too

**Comment by no23reason** [comment]
Hi, from the error it seems that location is not available in your version of Firefox (see [docs, code 2](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPositionError)). Please try upgrading it and trying again.
