### ISSUE TITLE
Increase frequency at which the position is updated

### ISSUE THREAD

**Issue by Nunobpinto** [no23reason/react-geolocated#432]
Hi, is there any way to increase the frequency at which the position is updated when the `watchPosition` option is set to `true`?

**Comment by Nunobpinto** [comment]
I've been reading the [Geolocation API Reference](https://www.w3.org/TR/2016/REC-geolocation-API-20161108/) and it kind of answered my question, the time it takes for `watchPosition` to be updated is dependent on the device itself, obviously in retrospect

**Comment by no23reason** [comment]
Hi, if you have the `maximumAge` parameter set to 0 (the default), I believe there is not much you can do to make it more frequent :-/
