### ISSUE TITLE
How to fetch location again onClick event

### ISSUE THREAD

**Issue by m-nathani** [no23reason/react-geolocated#507]
Hi,
is there a feature to fetch location again, i.e `Geolocation.getCurrentPosition()` method called to get the current position of the device or ask for the permission again on the onClick event..  ?

or is it possible to expose getLocation as a prop to get location..

**Comment by no23reason** [comment]
Hi, there is an example on how to do that using refs [in the demo](https://github.com/no23reason/react-geolocated/blob/master/demo/App.jsx#L14). Is that what you meant?

**Comment by m-nathani** [comment]
Yes, cool.. that's exactly what i was looking for. Will try using ref and see how it works. 

Thank for the prompt response.
Take care and stay safe )
