### ISSUE TITLE
How to make workable in android browser

### ISSUE THREAD

**Issue by mohaimenmahi** [no23reason/react-geolocated#514]
I used it into my code and it works fine in the Desktop browser, got the latitude and longitude but it is not getting the latitude and longitude when I open the app from my mobile browser. Can you help me with this? 

I tried the demo site you provided (https://no23reason.github.io/react-geolocated/) from my mobile browser and it shows me the latitude and longitude but don't know why it's not working for my react app.

**Comment by no23reason** [comment]
Hi, so if I understand correctly, the demo page works in your browser, but your app does not? Can you please share how you use the geolocated functions?

**Comment by iamir4g** [comment]
hi , i have same issue when run my app in my desktop ok, but when open it with safari on my iphone `isGeolocationEnabled` is false but my location service for safari is on?
this is my code :
```
return (<div>{props.isGeolocationAvailable? <p className={classes.errorTxt}> support </p> : <p className={classes.errorTxt}>not support</p> } 
    {props.isGeolocationEnabled ?<p className={classes.errorTxt}> enable</p>:<p className={classes.errorTxt}> not enable</p>} 
    {props.coords?<p className={classes.errorTxt}>lat:{props.coords.latitude} lng:{props.coords.longitude}</p> : <p className={classes.errorTxt}> geting locations</p>}
    <GoogleMap
        onLoad={loadHandler}
            mapContainerStyle={containerStyle}
            center={{ lat: props.prop.locations.YPOINT, lng: props.prop.locations.XPOINT }}
            zoom={18}
            options={{ gestureHandling: 'greedy', }}
            onClick={e => { 
                //    setClickedLatLng(e.latLng.toJSON());
                   setIsOpen(false) }}
        >
</Google>)

export default  geolocated({
    positionOptions: {
        enableHighAccuracy: true,
    },
    userDecisionTimeout: 2000,
})(React.memo(CurrentLocationMap));

```

**Comment by no23reason** [comment]
Hi, does the demo page work for you? https://no23reason.github.io/react-geolocated/ if not, there might be some problem with iOS permissions on your device. I tried it just now on my iPhone and it works fine.

**Comment by mohaimenmahi** [comment]
@no23reason Finally worked. Did nothing, just made the domain of the app SSL certified. Thanks anyway. I am closing that issue.
