### ISSUE TITLE
What happening when a user disable the geolocation on the browser popup

### ISSUE THREAD

**Issue by Jakub41** [no23reason/react-geolocated#656]
Hello,
I would like to ask a question about the 1 functionality you have. 
In the demo when I denied the geolocation and pressing the button again is just saying that geolocation not detected. 
There is a way to show again the popup of the browser instead or I need to make a custom dialog for it asking a user to do itself but that will require I need to include instructions as users are not all geek people knowing how to enable/disable geolocation from browser. 

To be clear the flow I need to reproduce:

1. Click the button
2. Popup of the browser shows
3. Click deny on the geolocation asking
4. click the button again
5. popup shows again

I hope my question is clear enough :)

Thank you
Jakub

**Comment by no23reason** [comment]
Hi, unfortunately, I do not think it is possible. Browsers do not allow you to ask again once you have declined. I assume this is to prevent "spammy" requests to enable the geolocation over and over again.

Please see relevant StackOverflow thread: https://stackoverflow.com/questions/20678707/ask-for-geolocation-permission-again-if-it-was-denied

**Comment by Jakub41** [comment]
Hi @no23reason  thanks for the answer :)

I have another question, could you suggest to me how to use that system inside a file?
I don't pass props to my component as it is a tab that opens automatically during a survey.
How can I use the geolocated stuff inside the same file as I do not pass props?

The file is this
https://pastebin.com/ebutmZc0

I have a function handleFindNearestSite which is a button when pressed is taking the location of a user to show on a map the nearest site. Here I would like to add that way of your package to check if geolocation is enabled and supported as your package is supported by safari and for me is important. 

So if you have any suggestion I may use would be great :) 

Thank you for your help and I like this package :P

**Comment by no23reason** [comment]
Hi @Jakub41, I don't think you can use this library like that. What you could do, is to create a component that handles just the nearest clinic and use the ref to refresh its data as seen in the [Demo](https://no23reason.github.io/react-geolocated/). Then you can also run some calculation or whatever logic you need :)

**Comment by no23reason** [comment]
Closing as inactive
