### ISSUE TITLE
Convert to React Hook

### ISSUE THREAD

**Issue by lauterry** [no23reason/react-geolocated#918]
Hi

Would be great to have this lib be usable as a react hook 

Best regards

**Comment by no23reason** [comment]
Hi, this has been suggested before: #414

Unfortunately, there are some challenges with some of the configuration props (i.e. we cannot just take the configuration items and make them parameters of the hook).

For example: what should happen when the `userDecisionTimeout` configuration changes?

- Should the underlying timeout be discarded and a new timeout created? But that would make the timeout longer by the time that has already elapsed.
- Should it ignore the changes to this config? But that would not be very "reactive".

I guess the correct approach would be to create a hook factory, something that would be used like

```ts
import { createUseGeolocated } from "react-geolocated";

const useGeolocated = createUseGeolocated(config); // this is what is currently in the Configuration options, like the userDecisionTimeout

const MyComponent = () => {
    const { coords } = useGeolocated({ onError, onSuccess });
}
```

However, this might be too confusing, I am not sure.

If you want to take a stab at this, please feel free to open a PR, I unfortunately do not have the capacity to do this myself these days 😞
